In [1]:
#45: Memadukan loc dan iloc untuk melakukan seleksi data

In [2]:
import pandas as pd
import numpy as np

print(pd.__version__)
print(np.__version__)

2.3.3
2.3.4

In [3]:
df = pd.read_csv('../data/titanicfull.csv')
df.head()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.00,0,0,24160,211.3375,B5,S
1,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,151.5500,C22 C26,S
2,1,0,"Allison, Miss. Helen Loraine",female,2.00,1,2,113781,151.5500,C22 C26,S
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.00,1,2,113781,151.5500,C22 C26,S
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.00,1,2,113781,151.5500,C22 C26,S

In [4]:
df.iloc[15:20, :].loc[:, 'name':'age']

                                               name     sex   age
15                              Baumann, Mr. John D    male   NaN
16                         Baxter, Mr. Quigg Edmond    male  24.0
17  Baxter, Mrs. James (Helene DeLaudeniere Chaput)  female  50.0
18                            Bazzani, Miss. Albina  female  32.0
19                             Beattie, Mr. Thomson    male  36.0

In [5]:
df.loc[:, 'name':'age'].iloc[15:20, :]

                                               name     sex   age
15                              Baumann, Mr. John D    male   NaN
16                         Baxter, Mr. Quigg Edmond    male  24.0
17  Baxter, Mrs. James (Helene DeLaudeniere Chaput)  female  50.0
18                            Bazzani, Miss. Albina  female  32.0
19                             Beattie, Mr. Thomson    male  36.0

In [6]:
#46: Seleksi weekdays dan weekends pada data deret waktu (time series)

In [7]:
n_rows = 365
n_cols = 2
cols = ['col1', 'col2']

df = pd.DataFrame(np.random.randint(1, 20, size=(n_rows, n_cols)), columns=cols)

df.index = pd.date_range(start='2024-01-01', periods=n_rows, freq='D')

print(df)

            col1  col2
2024-01-01     9     2
2024-01-02     4     5
2024-01-03     6    13
2024-01-04     7    10
2024-01-05     4     7
...          ...   ...
2024-12-26     8     4
2024-12-27     1    14
2024-12-28     2    18
2024-12-29     7     7
2024-12-30     7    19

[365 rows x 2 columns]

In [8]:
weekdays_df = df[df.index.dayofweek.isin([0, 1, 2, 3, 4])]
weekdays_df.head(7)

            col1  col2
2024-01-01     9     2
2024-01-02     4     5
2024-01-03     6    13
2024-01-04     7    10
2024-01-05     4     7
2024-01-08     9     7
2024-01-09    17    11

In [9]:
weekends_df = df[df.index.dayofweek.isin([5, 6])]
weekends_df.head(7)

            col1  col2
2024-01-06     2     8
2024-01-07     7    13
2024-01-13    13    19
2024-01-14    11     9
2024-01-20    13    19
2024-01-21    17     7
2024-01-27    11    15

In [10]:
#47: Deteksi dan penanganan kolom dengan tipe data beragam (mixed data types)

In [11]:
d = {'nama':['bejo', 'tejo', 'wati', 'tiwi', 'cecep'], 
     'ipk':[2, '3', 3, 2.75, '3.25']}
df = pd.DataFrame(d)
df

    nama   ipk
0   bejo     2
1   tejo     3
2   wati     3
3   tiwi  2.75
4  cecep  3.25

In [12]:
df.dtypes

nama    object
ipk     object
dtype: object

In [13]:
df['ipk'].apply(type)

0      <class 'int'>
1      <class 'str'>
2      <class 'int'>
3    <class 'float'>
4      <class 'str'>
Name: ipk, dtype: object

In [14]:
df['ipk'].apply(type).value_counts()

ipk
<class 'int'>      2
<class 'str'>      2
<class 'float'>    1
Name: count, dtype: int64

In [15]:
df['ipk'] = df['ipk'].astype(float)

In [16]:
df['ipk'].apply(type).value_counts()

ipk
<class 'float'>    5
Name: count, dtype: int64

In [17]:
#48: Mengenal Cummulative Count dengan cumcount()

In [18]:
d = {'penjual':['bejo', 'tejo', 'wati', 'bejo', 'cecep', 'tejo', 'wati', 'bejo'], 
     'barang':['monitor', 'monitor', 'keyboard', 'mouse', 'keyboard', 'monitor', 'laptop', 'monitor']}

df = pd.DataFrame(d)
df

  penjual    barang
0    bejo   monitor
1    tejo   monitor
2    wati  keyboard
3    bejo     mouse
4   cecep  keyboard
5    tejo   monitor
6    wati    laptop
7    bejo   monitor

In [19]:
df['count_tiap_penjual'] = df.groupby('penjual').cumcount() + 1
df

  penjual    barang  count_tiap_penjual
0    bejo   monitor                   1
1    tejo   monitor                   1
2    wati  keyboard                   1
3    bejo     mouse                   2
4   cecep  keyboard                   1
5    tejo   monitor                   2
6    wati    laptop                   2
7    bejo   monitor                   3

In [20]:
df['count_tiap_barang'] = df.groupby('barang').cumcount() + 1
df

  penjual    barang  count_tiap_penjual  count_tiap_barang
0    bejo   monitor                   1                  1
1    tejo   monitor                   1                  2
2    wati  keyboard                   1                  1
3    bejo     mouse                   2                  1
4   cecep  keyboard                   1                  2
5    tejo   monitor                   2                  3
6    wati    laptop                   2                  1
7    bejo   monitor                   3                  4

In [21]:
df['count_pasangan_kolom'] = df.groupby(['penjual', 'barang']).cumcount() + 1
df

,penjual,barang,count_tiap_penjual,count_tiap_barang,count_pasangan_kolom
0,bejo,monitor,1,1,1
1,tejo,monitor,1,2,1
2,wati,keyboard,1,1,1
3,bejo,mouse,2,1,1
4,cecep,keyboard,1,2,1
5,tejo,monitor,2,3,2
6,wati,laptop,2,1,1
7,bejo,monitor,3,4,2