In [1]:
#49: Seleksi kolom dengan f-string

In [2]:
import pandas as pd
import numpy as np

print(pd.__version__)
print(np.__version__)

2.3.3
2.3.4

In [4]:
df = pd.read_csv('../data/Iris.csv')
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [5]:
df['SepalWidthCm'].to_frame().head()

   SepalWidthCm
0           3.5
1           3.0
2           3.2
3           3.1
4           3.6

In [6]:
part = 'Sepal'

df[f'{part}WidthCm'].to_frame().head()

   SepalWidthCm
0           3.5
1           3.0
2           3.2
3           3.1
4           3.6

In [7]:
df[['PetalWidthCm', 'PetalLengthCm']].head()

   PetalWidthCm  PetalLengthCm
0           0.2            1.4
1           0.2            1.4
2           0.2            1.3
3           0.2            1.5
4           0.2            1.4

In [8]:
part = 'Petal'

df[[f'{part}WidthCm', f'{part}LengthCm']].head()

   PetalWidthCm  PetalLengthCm
0           0.2            1.4
1           0.2            1.4
2           0.2            1.3
3           0.2            1.5
4           0.2            1.4

In [9]:
#50: Membuat kolom baru dengan looping dan f-string

In [10]:
d = {'penjual':['bejo', 'tejo', 'wati', 'bejo', 'cecep', 'tejo', 'wati', 'bejo'], 
     'barang':['monitor', 'monitor', 'keyboard', 'mouse', 'keyboard', 'monitor', 'laptop', 'monitor']}

df = pd.DataFrame(d)
df

  penjual    barang
0    bejo   monitor
1    tejo   monitor
2    wati  keyboard
3    bejo     mouse
4   cecep  keyboard
5    tejo   monitor
6    wati    laptop
7    bejo   monitor

In [11]:
cols = ['penjual', 'barang']

for col in cols:
    df[f'count_tiap_{col}'] =  df.groupby(col).cumcount() + 1
    
df

  penjual    barang  count_tiap_penjual  count_tiap_barang
0    bejo   monitor                   1                  1
1    tejo   monitor                   1                  2
2    wati  keyboard                   1                  1
3    bejo     mouse                   2                  1
4   cecep  keyboard                   1                  2
5    tejo   monitor                   2                  3
6    wati    laptop                   2                  1
7    bejo   monitor                   3                  4

In [12]:
#51: Seleksi baris dengan between()

In [13]:
n_rows = 10
n_cols = 5
cols = tuple('ABCDE')

df = pd.DataFrame(np.random.randint(1, 10, size=(n_rows, n_cols)), 
                  columns=cols)
df

   A  B  C  D  E
0  7  4  7  8  5
1  8  1  3  5  9
2  7  7  8  1  8
3  4  7  3  9  8
4  3  5  1  7  1
5  7  4  1  5  9
6  6  5  4  9  1
7  5  6  5  4  2
8  7  4  1  1  2
9  4  1  3  1  5

In [14]:
df[df['A'].between(2, 5)]

   A  B  C  D  E
3  4  7  3  9  8
4  3  5  1  7  1
7  5  6  5  4  2
9  4  1  3  1  5

In [15]:
df[df['A'].between(2, 5, inclusive='left')]

   A  B  C  D  E
3  4  7  3  9  8
4  3  5  1  7  1
9  4  1  3  1  5

In [16]:
df[df['A'].between(2, 5, inclusive='right')]

   A  B  C  D  E
3  4  7  3  9  8
4  3  5  1  7  1
7  5  6  5  4  2
9  4  1  3  1  5

In [17]:
df[df['A'].between(2, 5, inclusive='both')]

   A  B  C  D  E
3  4  7  3  9  8
4  3  5  1  7  1
7  5  6  5  4  2
9  4  1  3  1  5

In [18]:
df[df['A'].between(2, 5, inclusive='neither')]

   A  B  C  D  E
3  4  7  3  9  8
4  3  5  1  7  1
9  4  1  3  1  5

In [19]:
#52: Transformasi kolom menjadi baris pada Data Frame

In [20]:
d = {
'kode_area': [123, 456, 789, 321],
'pabrik': [4, 2, 5, 0],
'gudang': [2, 4, 7, 3],
'toko': [64, 32, 15, 24]
}

df = pd.DataFrame(d)
df

   kode_area  pabrik  gudang  toko
0        123       4       2    64
1        456       2       4    32
2        789       5       7    15
3        321       0       3    24

In [21]:
df = df.melt(id_vars='kode_area', 
             var_name='jenis_bangunan', 
             value_name='jumlah')
df

    kode_area jenis_bangunan  jumlah
0         123         pabrik       4
1         456         pabrik       2
2         789         pabrik       5
3         321         pabrik       0
4         123         gudang       2
5         456         gudang       4
6         789         gudang       7
7         321         gudang       3
8         123           toko      64
9         456           toko      32
10        789           toko      15
11        321           toko      24