In [10]:
#33: Menampilkan nilai kumulatif (cummulative)

In [1]:
import pandas as pd

print(pd.__version__)

2.3.3

In [2]:
d = {'pemain':['Budi', 'Joni', 'Iwan', 'Budi', 'Budi', 'Iwan', 'Asep', 'Joni'], 
     'goal':[2, 1, 3, 1, 1, 2, 2, 3]}
df = pd.DataFrame(d)
df

  pemain  goal
0   Budi     2
1   Joni     1
2   Iwan     3
3   Budi     1
4   Budi     1
5   Iwan     2
6   Asep     2
7   Joni     3

In [3]:
df['goal'].cumsum().to_frame()

   goal
0     2
1     3
2     6
3     7
4     8
5    10
6    12
7    15

In [4]:
df['jumlah_goal_kumulatif'] = df['goal'].cumsum()
df

  pemain  goal  jumlah_goal_kumulatif
0   Budi     2                      2
1   Joni     1                      3
2   Iwan     3                      6
3   Budi     1                      7
4   Budi     1                      8
5   Iwan     2                     10
6   Asep     2                     12
7   Joni     3                     15

In [5]:
df['jumlah_goal_kumulatif_tiap_pemain'] = df.groupby('pemain')['goal'].cumsum()
df

  pemain  goal  jumlah_goal_kumulatif  jumlah_goal_kumulatif_tiap_pemain
0   Budi     2                      2                                  2
1   Joni     1                      3                                  1
2   Iwan     3                      6                                  3
3   Budi     1                      7                                  3
4   Budi     1                      8                                  4
5   Iwan     2                     10                                  5
6   Asep     2                     12                                  2
7   Joni     3                     15                                  4

In [6]:
df['cummax'] = df['goal'].cummax()
df

,pemain,goal,jumlah_goal_kumulatif,jumlah_goal_kumulatif_tiap_pemain,cummax
0,Budi,2,2,2,2
1,Joni,1,3,1,2
2,Iwan,3,6,3,3
3,Budi,1,7,3,3
4,Budi,1,8,4,3
5,Iwan,2,10,5,3
6,Asep,2,12,2,3
7,Joni,3,15,4,3

In [7]:
df['cummin'] = df['goal'].cummin()
df

,pemain,goal,jumlah_goal_kumulatif,jumlah_goal_kumulatif_tiap_pemain,cummax,cummin
0,Budi,2,2,2,2,2
1,Joni,1,3,1,2,1
2,Iwan,3,6,3,3,1
3,Budi,1,7,3,3,1
4,Budi,1,8,4,3,1
5,Iwan,2,10,5,3,1
6,Asep,2,12,2,3,1
7,Joni,3,15,4,3,1

In [8]:
df['cumprod'] = df['goal'].cumprod()
df

,pemain,goal,jumlah_goal_kumulatif,jumlah_goal_kumulatif_tiap_pemain,cummax,cummin,cumprod
0,Budi,2,2,2,2,2,2
1,Joni,1,3,1,2,1,2
2,Iwan,3,6,3,3,1,6
3,Budi,1,7,3,3,1,6
4,Budi,1,8,4,3,1,6
5,Iwan,2,10,5,3,1,12
6,Asep,2,12,2,3,1,24
7,Joni,3,15,4,3,1,72

In [9]:
#34: Mapping pada Data Frame dengan applymap()

In [11]:
d = {'pemain':['Budi', 'Joni', 'Iwan', 'Budi', 'Budi', 'Iwan', 'Asep', 'Joni'], 
     'goal':[2, 1, 3, 1, 1, 2, 2, 3]}
df = pd.DataFrame(d)
df

  pemain  goal
0   Budi     2
1   Joni     1
2   Iwan     3
3   Budi     1
4   Budi     1
5   Iwan     2
6   Asep     2
7   Joni     3

In [12]:
df['goal'].cumsum().to_frame()

   goal
0     2
1     3
2     6
3     7
4     8
5    10
6    12
7    15

In [13]:
df['jumlah_goal_kumulatif'] = df['goal'].cumsum()
df

  pemain  goal  jumlah_goal_kumulatif
0   Budi     2                      2
1   Joni     1                      3
2   Iwan     3                      6
3   Budi     1                      7
4   Budi     1                      8
5   Iwan     2                     10
6   Asep     2                     12
7   Joni     3                     15

In [14]:
df['jumlah_goal_kumulatif_tiap_pemain'] = df.groupby('pemain')['goal'].cumsum()
df

  pemain  goal  jumlah_goal_kumulatif  jumlah_goal_kumulatif_tiap_pemain
0   Budi     2                      2                                  2
1   Joni     1                      3                                  1
2   Iwan     3                      6                                  3
3   Budi     1                      7                                  3
4   Budi     1                      8                                  4
5   Iwan     2                     10                                  5
6   Asep     2                     12                                  2
7   Joni     3                     15                                  4

In [15]:
df['cummax'] = df['goal'].cummax()
df

,pemain,goal,jumlah_goal_kumulatif,jumlah_goal_kumulatif_tiap_pemain,cummax
0,Budi,2,2,2,2
1,Joni,1,3,1,2
2,Iwan,3,6,3,3
3,Budi,1,7,3,3
4,Budi,1,8,4,3
5,Iwan,2,10,5,3
6,Asep,2,12,2,3
7,Joni,3,15,4,3

In [16]:
df['cummin'] = df['goal'].cummin()
df

,pemain,goal,jumlah_goal_kumulatif,jumlah_goal_kumulatif_tiap_pemain,cummax,cummin
0,Budi,2,2,2,2,2
1,Joni,1,3,1,2,1
2,Iwan,3,6,3,3,1
3,Budi,1,7,3,3,1
4,Budi,1,8,4,3,1
5,Iwan,2,10,5,3,1
6,Asep,2,12,2,3,1
7,Joni,3,15,4,3,1

In [17]:
df['cumprod'] = df['goal'].cumprod()
df

,pemain,goal,jumlah_goal_kumulatif,jumlah_goal_kumulatif_tiap_pemain,cummax,cummin,cumprod
0,Budi,2,2,2,2,2,2
1,Joni,1,3,1,2,1,2
2,Iwan,3,6,3,3,1,6
3,Budi,1,7,3,3,1,6
4,Budi,1,8,4,3,1,6
5,Iwan,2,10,5,3,1,12
6,Asep,2,12,2,3,1,24
7,Joni,3,15,4,3,1,72

In [18]:
#35: Memadukan fungsi agregasi dengan transform()

In [19]:
d = {'no_nota':[1, 1, 1, 2, 2, 3, 4, 5], 
     'kopi': ['latte', 'cappuccino', 'espresso', 'latte', 'espresso', 'cappuccino', 'latte', 'espresso'],
     'harga':[50, 60, 80, 150, 120, 60, 100, 40]}

df = pd.DataFrame(d)
df

   no_nota        kopi  harga
0        1       latte     50
1        1  cappuccino     60
2        1    espresso     80
3        2       latte    150
4        2    espresso    120
5        3  cappuccino     60
6        4       latte    100
7        5    espresso     40

In [20]:
df.groupby('no_nota')['harga'].sum().to_frame()

         harga
no_nota
1          190
2          270
3           60
4          100
5           40

In [21]:
df['total_harga'] = df.groupby('no_nota')['harga'].transform(sum)
df

C:\Users\josua\AppData\Local\Temp\ipykernel_15228\2648411243.py:1: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  df['total_harga'] = df.groupby('no_nota')['harga'].transform(sum)

   no_nota        kopi  harga  total_harga
0        1       latte     50          190
1        1  cappuccino     60          190
2        1    espresso     80          190
3        2       latte    150          270
4        2    espresso    120          270
5        3  cappuccino     60           60
6        4       latte    100          100
7        5    espresso     40           40

In [22]:
df.groupby('kopi')['harga'].sum().to_frame()

            harga
kopi
cappuccino    120
espresso      240
latte         300

In [23]:
df['total_omset'] = df.groupby('kopi')['harga'].transform(sum)
df

C:\Users\josua\AppData\Local\Temp\ipykernel_15228\280329391.py:1: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  df['total_omset'] = df.groupby('kopi')['harga'].transform(sum)

   no_nota        kopi  harga  total_harga  total_omset
0        1       latte     50          190          300
1        1  cappuccino     60          190          120
2        1    espresso     80          190          240
3        2       latte    150          270          300
4        2    espresso    120          270          240
5        3  cappuccino     60           60          120
6        4       latte    100          100          300
7        5    espresso     40           40          240

In [24]:
#36: Menyatukan kolom dengan str.cat()

In [25]:
data = {'nama': ['bayu', 'indra', 'devi', 'agni'],
        'jenis_kelamin': ['L', 'L', 'P', 'L'], 
        'usia': [23, 21, 22, 25]}

df = pd.DataFrame(data)
df

    nama jenis_kelamin  usia
0   bayu             L    23
1  indra             L    21
2   devi             P    22
3   agni             L    25

In [26]:
df['nama'].str.cat(df['jenis_kelamin'], sep=', ').to_frame()

       nama
0   bayu, L
1  indra, L
2   devi, P
3   agni, L

In [27]:
df['nama_jk'] = df['nama'].str.cat(df['jenis_kelamin'], sep=', ')
df

    nama jenis_kelamin  usia   nama_jk
0   bayu             L    23   bayu, L
1  indra             L    21  indra, L
2   devi             P    22   devi, P
3   agni             L    25   agni, L

In [28]:
df['nama'].str.cat(df['usia'].astype('str'), sep=' - ').to_frame()

         nama
0   bayu - 23
1  indra - 21
2   devi - 22
3   agni - 25

In [29]:
df['nama_usia'] = df['nama'].str.cat(df['usia'].astype('str'), sep=' - ')
df

    nama jenis_kelamin  usia   nama_jk   nama_usia
0   bayu             L    23   bayu, L   bayu - 23
1  indra             L    21  indra, L  indra - 21
2   devi             P    22   devi, P   devi - 22
3   agni             L    25   agni, L   agni - 25